<?php
use JqGridBackend\Grid\View\Helper\Grid as GridHelper;
use Zend\Json\Json;

/** @var GridHelper $grid */
$grid = $this->grid;
$gridName = 'Grid' . $grid->getName();
$gridObject = $this->object;
$gridOptions = $grid->getGridOptions($gridObject);

if (array_key_exists('pager', $gridOptions)) {
    $pagerId = str_replace('#', '', strval($gridOptions['pager']));
} else {
    $pagerId = 'undefined';
}
?>
function(subgrid_id, row_id) {
    var subgrid_table_id;
    subgrid_table_id = '<?php echo $gridName; ?>'+subgrid_id+"_t";
    var subgrid_pager_id = <?php echo $pagerId ?>;

    var subgridHtmlBlock = "<table id=\'"+subgrid_table_id+"\' class=\'scroll\' style='width:100%;'></table>";
    if (subgrid_pager_id != undefined) {
        subgridHtmlBlock += "<div id=\'"+subgrid_pager_id+"\'></div>";
    }
    jQuery("#"+subgrid_id).html(subgridHtmlBlock);

<?php
    printf("var %s = jQuery('#'+subgrid_table_id).jqGrid(\n",
        $gridName, $gridName
    );
    echo Json::encode($grid->getBody($gridObject), false, [ 'enableJsonExprFinder'=>true, 'prettyPrint'=>true ]);
    printf(");\n");
    foreach ($grid->getGridMethods($gridObject) as $methodData) {
        $str = '';
        $str .= Json::encode($methodData, false, [ 'enableJsonExprFinder'=>true ]);
        if ($str != '') {
            $str = $gridName . '.jqGrid('. $str . ");\n";
            echo $str;
        }
    }

?>
}

